name: Theme Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  trigger-wp-workflow:
    runs-on: [self-hosted, doctorparts-host]
    steps:
      - name: Trigger WP Workflow
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'wordpress',
              workflow_id: 'deploy.yml',
              ref: 'master',
            })