name: Theme Deploy

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  checkout:
    runs-on: [self-hosted, doctorparts-host]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with: 
          submodules: true
          lfs: true
          ref: 'master'

      - name: Update submodules
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

  build:
    runs-on: [self-hosted, doctorparts-host]
    needs: checkout
    steps:
      - uses: actions/setup-node@v3
      
      - name: Cache npm packages
        id: npm-wordpress-theme-js-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-wordpress-theme-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-wordpress-theme-npm-
            
      - name: Cache WP Composer packages
        id: composer-wordpress-theme-php-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-wordpress-theme-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-wordpress-theme-php-
      
      - name: Install dependecies
        run: |
          npm i
          composer install

  release:
    runs-on: [self-hosted, doctorparts-host]
    needs: build
    steps:
      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''
          tag_template: 'yyyy.mm.dd.i'

      - name: Theme packing
        run: |
          cd ..
          mkdir xp-theme
          cp -r ./wordpress-theme/* ./xp-theme/
          zip ./wordpress-theme/xp-theme-${{ steps.generate_release_tag.outputs.next_release_tag }}.zip -r ./xp-theme/
          rm -rf ./xp-theme
          cd ./wordpress-theme

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: 'master'
          tag_name: v${{ steps.generate_release_tag.outputs.next_release_tag }}
          release_name: Release v${{ steps.generate_release_tag.outputs.next_release_tag }}
          body: Automatic CI Release by ${{ github.actor }} at ${{ github.ref }} reference
          draft: false
          prerelease: false
