name: Theme Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  trigger-wp-workflow:
    runs-on: [self-hosted, doctorparts-host]
    steps:
      - name: Trigger WP Workflow
        uses: convictional/trigger-workflow-and-wait
        with:
          owner: xparty-ent
          repo: wordpress
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_file_name: deploy.yml
          ref: master
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true